steps:
  - label: ":building_construction: Build"
    key: "build"
    commands:
      - chmod +x .buildkite/scripts/build.sh
      - .buildkite/scripts/build.sh
    plugins:
      - docker#v3.13.0:
          propagate-environment: true
          image: "node:latest" 
          workdir: /app
    artifact_paths:
      - ./dist/**/*
      

  - label: ":terraform: Deploy"
    key: "deploy"
    depends_on: "build"
    commands:
      - chmod +x .buildkite/scripts/deploy.sh
      - .buildkite/scripts/deploy.sh
    plugins:
      - docker#v3.5.0:
          propagate-environment: true
          entrypoint: ""
          shell: ["/bin/sh", "-c"]
          image: "hashicorp/terraform:latest"
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::695663959248:role/S3Admin"