steps:
  - label: ":building_construction: Build"
    key: "build"
    commands:
      - chmod +x .buildkite/scripts/build.sh
      - .buildkite/scripts/build.sh
    plugins:
      - docker#v3.13.0:
          mount-ssh-agent: true
          propagate-environment: true
          image: "node:latest" 
          workdir: /app
    artifact_paths:
      - ./dist/**/*    