steps:
  - label: ":building_construction: Build"
    key: "build"
    commands:
      - echo "All users........."
      - cat /etc/passwd
      - echo "subuid........."
      - cat /etc/subuid
      - echo "subgid........."
      - cat /etc/subgid
      - pwd
      - ls -ltr
      - chmod +x .buildkite/scripts/build.sh
      - .buildkite/scripts/build.sh
      - pwd
      - ls -ltr
    plugins:
      - docker#v3.5.0:
          mount-ssh-agent: true
          propagate-environment: true
          image: "node:latest" 
          workdir: /app
    artifact_paths:
      - ./dist/**/*


  - label: ":terraform: Deploy"
    key: "deploy"
    depends_on: "build"
    commands:
      - chmod +x .buildkite/scripts/deploy.sh
      - .buildkite/scripts/deploy.sh
    plugins:
      - docker#v3.5.0:
          mount-ssh-agent: true
          propagate-environment: true
          propagate-aws-auth-token: true
          entrypoint: ""
          shell: ["/bin/sh", "-c"]
          image: "hashicorp/terraform:latest"      